### ISSUE TITLE
한국 이름 한글표기 가능성 관련

### ISSUE THREAD

**Issue by PARAdoxiBLE** [whiteforce4/Democracy4KoreanTranslation#27]
사실 모드에서 아마 못 하는 부분일 것 같은데, Democracy 4\data\names 가면 나오는 southkoreannames.txt 파일에 직접 한글로 이름을 작성하면 인게임에 표시가 됨. 다만 문제가 조금 있는데

**이름+성** 원문 자체가 이렇게 되어있어서 이름 '이병철'은 'Byungchul Lee' 하는 식으로 표시가 되는 중임. 당연히 Byungchul과 Lee를 각각 병철과 이로 옮겨도 인게임에서 '병철 이' 라는 졸라 어색한 이름이 나올 뿐임. 개발자한테 물어보면 바꿔줄지도 모르겠지만 암튼 당장은 이렇게 되어있음.

그렇다고 이름과 성의 내용물을 교체하는 꼼수도 별로 내키지 않는게, 이름은 [maleforenames]와 [femaleforenames]로 구성되고 성은 [surnames] 하나로만 되어있는데, 이름은 남성 여성 양쪽 다 똑같이 성씨로 채우고 이름을 남녀이름을 모두 적는 방식의 꼼수를 쓰면 남자이름 여자이름을 구별해서 생성하는 것이 불가능해짐. 게다가 이름과 성 사이에 당연히 공백이 존재하기 때문에 저짓을 해도 '이 병철' 같은 이름이 나오게 됨.

그래서 일단 지금 개인적으로 사용중인 2차 꼼수는, 랜덤으로 미리 성씨와 이름을 조합한 적당한 갯수의 이름 목록을 성별별로 만들어서 각각을 [maleforenames]와 [femaleforenames]에 쓰고 (성씨+이름인 '이병철' 자체가 [maleforenames]에 들어있는 식) [surnames]에는 유니코드에서 가장 작은 공백 특수문자([https://www.compart.com/en/unicode/U+200A](https://www.compart.com/en/unicode/U+200A))를 집어넣는 것임.

> [surnames]
 

이렇게 하면 이름을 조합한다는 기능 자체는 완전히 망가지고 ([name]+[surname]=[성씨+이름]+[hair space] 이렇게 해버리는 셈이니) 그냥 미리 파일에 적어둔 이름 400개정도를 돌려쓰게 되지만 적어도 성별구분은 잘 하고 성씨와 이름을 붙여써서 보여주기 때문에 개인적으로 이 쪽이 더 자연스러웠음.

사실 한글화 모드에서 어떻게 할 수 있는 내용은 아니니 크게 관련은 없는거지만 일단 가져와봤음. 사실 마음같아선 이름파일도 한글로 옮길 수 있었으면 좋겠긴 함.

+추가내용: 이름 번역은 새로 이름을 생성할 때부터 적용이 됨. 따라서 이걸 적용하기 전에 이미 진행중이던 게임을 불러오면 장관이나 장관 후보자 이름이 여전히 영어로 나옴.

**Comment by whiteforce4** [comment]
번역 좀 정리되면 개발자한테 물어보겠습니다. 만약 안된다고 하면 2차 꼼수 써버리죠
