### ISSUE TITLE
1.26 텍스트 원문 변화

### ISSUE THREAD

**Issue by PARAdoxiBLE** [whiteforce4/Democracy4KoreanTranslation#30]
[1.26]
1) Removed duplicate effect from firearms laws to armed religious communities.
2) Removed duplicate impacts on luddite riots.
3) Fixed some harmless debug warnings about missing neurons.
4) Intel readouts are now inverted for situations where a policy reduces security effectiveness, such as Press Freedom.
5) Fixed error where a total ban on handguns actually reduced security, instead of boosting it. Ooops.
6) Fixed support for names for each slider setting in modded policies.
7) EU situation now renamed to EU membership, also now boosts stability and foreign investment.
8) EU countries now benefit from the Erasmus programme, which boosts youth income & happiness and also education.
9) Import tariffs can now not be implemented by EU members.
10) Made some impacts of banning low mpg cars scaled by EV transition, and introduced support for inverse variables and 6-variable equations.
11) Cyberbullying Awareness Policy now slightly reduces Internet Crime.
12) Universal Basic Income (UBI) cost now quadrupled so it reflects the correct figure.
13) The Polarization situation now explains its effects better.
14) Fixed some places where non English text was missing or did not fit nicely.
[https://steamcommunity.com/app/1410710](https://steamcommunity.com/app/1410710)

-------

**situations.csv**
변경 전

> #,EUContribution,EU **_Contribution_**,"As one of the wealthier and more economically stable nations in the EU, you pay a net contribution to the EU government to help support the European economy.",,
> #,EUSubsidies,EU **_Subsidies_**,"As one of the less developed nations in the EU, you receive subsidies from the EU government to help support the local economy.",,
> #,EUMonetaryPolicy,EU Monetary Policy,"As a member of the European union, decisions on monetary policy are taken by the European Central Bank and are thus not directly under our control. The EU has been utilizing a policy of Quantitative Easing to boost the economy for some time.",,
> #,Monarchy,Monarchy,"Britain is a Constitutional Monarchy, where the Queen is head of state, but has no real power and whose role is entirely ceremonial. Despite this, the queen meets weekly with the prime minister and likely exerts unofficial influence. The existence of the monarchy also perpetuates the hierarchical class system in the UK, together with similar institutions such as the House of Lords.",,
> 

변경후

> #,EUContribution,EU **_Membership_**,"As one of the wealthier and more economically stable nations in the EU, you pay a net contribution to the EU government to help support the European economy.",,
> #,EUSubsidies,EU **_Membership_**,"As one of the less developed nations in the EU, you receive subsidies from the EU government to help support the local economy.",,
> #,EUMonetaryPolicy,EU Monetary Policy,"As a member of the European union, decisions on monetary policy are taken by the European Central Bank and are thus not directly under our control. The EU has been utilizing a policy of Quantitative Easing to boost the economy for some time.",,
> #,Monarchy,Monarchy,"Britain is a Constitutional Monarchy, where the Queen is head of state, but has no real power and whose role is entirely ceremonial. Despite this, the queen meets weekly with the prime minister and likely exerts unofficial influence. The existence of the monarchy also perpetuates the hierarchical class system in the UK, together with similar institutions such as the House of Lords.",,
> **_#,Erasmus,Erasmus Programme,"Erasmus is the EU's programme to support education, training, youth and sport in Europe. Each year over 900,000 people study, train or volunteer abroad with support from the erasmus programme, which works with over 100,000 different organizations and 25,000 projects throughout the EU.",,_**

------

**sliders.csv**
**변경전**

> **_#,directdemocracy,DISTRICT VOTES,REGIONAL VOTES,FEDERAL STATE VOTES,REFERENDUM REQUESTS,CONSTITUTIONAL CHANGES,,,,,,,,,,,_**
> **_#,extinctspecies,CHICKEN BREEDS,CATTLE BREEDS,PIG BREEDS,MONKEYS AND APES,DODOS,VELOCIRAPTORS,T-REX,,,,,,,,,_**

> #,nukes,BOMBERS,ICBM,SUBMARINE-LAUNCHED,SUB-LAUNCHED MIRVs,ORBITAL BOMBERS,,,,,,,,,,,

**변경후**

> **_,,,,,,,,,,,,,,,,,_**
> **_,,,,,,,,,,,,,,,,,_**

> #,nukes,BOMBERS**_,LONG RANGE BOMBERS,MISSILES_**,ICBM,SUBMARINE-LAUNCHED,SUB-LAUNCHED MIRVs,ORBITAL BOMBERS,,,,,,,,,

-------------

**strings.ini**
**변경전**

> [strings]
> CUST_OPTIONS_SOCIAL_TT		= "Skews higher or lower the extent to which voters identify as socialists instead of capitalists."

**변경후**

> [strings]
> **_POLARIZATION_DESC 		= "Polarization directly affects the voters, making them more extreme, and more likely to drift towards hard left or right or liberal or conservative points of view."_**
> 
> CUST_OPTIONS_SOCIAL_TT		= "Skews higher or lower the extent to which voters identify as socialists instead of capitalists."

-----

**Comment by PARAdoxiBLE** [comment]
**요약**

situations.csv - 유럽연합 분담금/지원금의 명칭이 모두 유럽연합 회원국으로 통합, 유럽연합 국가들에 '에라스무스 프로그램' 이라는 상황이 추가됨
sliders.csv - 게임 내에 등장하지 않는 정책의 슬라이더 텍스트가 삭제, 핵무기 슬라이더 단계 세분화
strings.ini - 정치적 양극화 관련 설명이 추가되었는데 어디에 나오는건지는 잘 모르겠음 그래도 맥락이 그렇게 중요하지는 않을 것 같음

**Comment by whiteforce4** [comment]
일단 반영했습니다. 슬라이더 텍스트 삭제는 이미 삭제가 되었나 안보이네요..?
