### ISSUE TITLE
210506 패치 텍스트 변동내역

### ISSUE THREAD

**Issue by PARAdoxiBLE** [whiteforce4/Democracy4KoreanTranslation#48]
situations.csv 마지막줄에 다음 내용이 추가됨

> #,Bureaucracy,Bureaucracy,"When the government has too many policies, too many laws, and too much in the way of administration, it can become a drag on the economy. If a citizen needs to fill out a hundred forms in triplicate before starting a new business (or expanding one) they are likely to give up, or head to a more business friendly country.",Too much bureaucracy is causing a drag on the economy,A more streamlined system of policies and laws has reduced the bureaucratic burden on the economy.

-----

strings.ini 앞부분 변동

변경전

> [strings]
> POLARIZATION_DESC 		= "Polarization directly affects the voters, making them more extreme, and more likely to drift towards hard left or right or liberal or conservative points of view."

변경후

> [strings]
> BUREAUCRACY_DESC		= "Too many laws and policies will result in an overload of bureaucracy. Try cutting back on unnecessary legislation!"
> MINISTER_AVERAGE_EFFECTIVENESS	= "Average Minister Effectiveness:"
> MINISTER_EFFECTIVENESS		= "Minister Effectiveness:"
> CORRUPTION			= "Corruption:"
> 
> POLARIZATION_DESC 		= "Polarization directly affects the voters, making them more extreme, and more likely to drift towards hard left or right or liberal or conservative points of view."

-----

현재 열린 pull request 처리 후 적용하는걸로

**Comment by whiteforce4** [comment]
적용되었습니다.
